name: Photographer
favicon: null
layout_spectrum: 0.29448
typography_spectrum: 0.5518946482334286
title: Occasional places
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#191919'
    - '#c1c1c1'
    - '#727272'
    - '#9e9e9e'
  brandStrength: 0.5
  lightness: 0.3675206822808832
  saturation: 0.8130420653615147
  rhythmicContrast: 0.7844406927470118
purpose: []
