name: Photographer
favicon: null
layout_spectrum: 0.6090310101862997
typography_spectrum: 0.5518946482334286
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.03152018622495234
  lightness: 0.3675206822808832
  saturation: 0.8130420653615147
  rhythmicContrast: 0.7844406927470118
purpose: []
