name: Photographer
favicon: null
layout_spectrum: 0.52922
typography_spectrum: 1
title: Occasional places
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfbfb'
    - '#191919'
    - '#c1c1c1'
    - '#727272'
    - '#9e9e9e'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
