title: Occasional places
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5680851
  brandStrength: 0.0625
  lightness: 0.375
  brandColors:
    - '#fbfbfb'
    - '#191919'
    - '#c1c1c1'
    - '#727272'
    - '#9e9e9e'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Photographer
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 0.80622
